Fix printsupport in .pro file (#557)
This may be required to avoid errors like:

    src/kiwixapp.cpp:12:10: fatal error: QPrinter: No such file or directory